routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function() {
	Route::namespace('Auth')->middleware('guest:admin')->group(function() {
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
	});

	Route::middleware('auth:admin')->group(function() {
		Route::namespace('Auth')->group(function() {
			Route::post('logout', 'LoginController@logout')->name('logout');
		});

		Route::get('/', 'DashboardController@index')->name('dashboard');
		Route::get('/account_settings', 'DashboardController@accountSettings')->name('account_settings');
		Route::post('/account_settings', 'DashboardController@updateAccountSettings')->name('update_account_settings');
		
		Route::get('/admins', 'AdminController@index')->name('admins.index');
		Route::get('/permissions', 'PermissionController@index')->name('permissions.index');
		Route::get('/activity_logs', 'ActivityLogController@index')->name('activity_logs');

		/** Sample */
		Route::get('/samples', 'SampleController@index')->name('samples.index');
		Route::get('/samples/create', 'SampleController@create')->name('samples.create');
		Route::get('/samples/{id}', 'SampleController@show')->name('samples.show');
		Route::get('/samples/{id}/edit', 'SampleController@edit')->name('samples.edit');
		Route::get('/samples/{id}/destroy', 'SampleController@destroy')->name('samples.destroy');

		Route::post('/samples', 'SampleController@store')->name('samples.store');
		Route::post('/samples/{id}', 'SampleController@update')->name('samples.update');

		/** Roles */
		Route::get('/roles', 'RoleController@index')->name('roles.index');
		Route::get('/roles/create', 'RoleController@create')->name('roles.create');
		Route::get('roles/{id}/edit', 'RoleController@edit')->name('roles.edit');
		Route::get('/roles/{id}/destroy', 'RoleController@destroy')->name('roles.destroy');

		/** Users */
		Route::get('/users', 'UserController@index')->name('users.index');
		Route::get('/users/{id}', 'UserController@show')->name('users.show');

		Route::post('/roles', 'RoleController@store')->name('roles.store');
		Route::post('/roles/{id}', 'RoleController@update')->name('roles.update');
	});
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::namespace('Web')->name('web.')->group(function() {
	Route::namespace('Auth')->group(function() {
		Route::middleware('guest:web')->group(function() {
			Route::get('login', 'LoginController@showLoginForm')->name('login');
			Route::post('login', 'LoginController@login')->name('login');
		});
	});
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Spatie\Permission\Models\Role;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class RoleController extends Controller
{
	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    	$roles = Role::all();

    	return view('admin.pages.roles.index', [
    		'roles' => $roles,
    	]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::findOrfail($id);

        return view('admin.pages.roles.edit', [
            'role' => $role,
        ]);
    }
}

resources/views/admin/pages/roles/create.blade.php
@extends('admin.layouts.master')

@section('pageTitle', 'Create Role')

@section('content')
	<div class="content-wrapper">
	    <!-- Content Header (Page header) -->
	    <div class="content-header">
	        <div class="container-fluid">
	            <div class="row mb-2">
	                <div class="col-sm-6">
	                    <h1 class="m-0 text-dark">Add Roles</h1>
	                </div><!-- /.col -->
	                
	                <div class="col-sm-6">
	                    <ol class="breadcrumb float-sm-right">
	                        <li class="breadcrumb-item"><a href="#">Roles</a></li>
	                        <li class="breadcrumb-item active">Create</li>
	                    </ol>
	                </div><!-- /.col -->
	            </div><!-- /.row -->
	        </div><!-- /.container-fluid -->
	    </div>
	    <!-- /.content-header -->

	    <!-- Main content -->
	    <div class="content">
	        <div class="container-fluid">
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="card card-primary card-outline">
	                        <div class="card-body">
	                            <p class="card-text">
	                                {{--  --}}
	                            </p>

	                            <div class="row">
	                            	<div class="col-md-12">
	                            		<form action="{{ route('admin.roles.store') }}" method="POST">
	                            			@csrf

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                        <label for="name">Name</label>
				                                        <input name="name" type="text" class="form-control" id="name" placeholder="Name" value="{{ old('name') }}" required>
				                                    </div>
	                            				</div>
	                            			</div>

	                            			<div class="row">
												<div class="col-md-1">
		                            				<div class="form-group">
		                            					<button class="btn btn-primary form-control">Submit</button>
		                            				</div>
	                            				</div>
	                            			</div>
	                            		</form>
	                            	</div>
	                            	<!-- /.col-md-12 -->
					            </div>
					            <!-- /.row -->
	                        </div>
	                    </div>
	                    <!-- /.card -->
	                </div>
	                <!-- /.col-md-12 -->
	            </div>
	            <!-- /.row -->
	        </div>
	        <!-- /.container-fluid -->
	    </div>
	    <!-- /.content -->
	</div>
@endsection

resources/views/admin/pages/roles/edit.blade.php
@extends('admin.layouts.master')

@section('pageTitle', 'Sample')

@section('content')
	<div class="content-wrapper">
	    <!-- Content Header (Page header) -->
	    <div class="content-header">
	        <div class="container-fluid">
	            <div class="row mb-2">
	                <div class="col-sm-6">
	                    <h1 class="m-0 text-dark">Edit Role</h1>
	                </div><!-- /.col -->
	                
	                <div class="col-sm-6">
	                    <ol class="breadcrumb float-sm-right">
	                        <li class="breadcrumb-item"><a href="#">Roles</a></li>
	                        <li class="breadcrumb-item active"><a href="#">Edit</a></li>
	                    </ol>
	                </div><!-- /.col -->
	            </div><!-- /.row -->
	        </div><!-- /.container-fluid -->
	    </div>
	    <!-- /.content-header -->

	    <!-- Main content -->
	    <div class="content">
	        <div class="container-fluid">
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="card card-primary card-outline">
	                        <div class="card-body">
	                            <p class="card-text">
	                                Role
	                            </p>

	                            <div class="row">
	                            	<div class="col-md-12">
	                            		<table id="role_users" class="table table">
	                            			<thead>
	                            				<tr>
	                            					<th>ID</th>
	                            					<th>Name</th>
	                            					<th>Email</th>
	                            					<th>Actions</th>
	                            				</tr>
	                            			</thead>

	                            			<tbody>
	                            				<tr>
	                            					<td></td>
	                            					<td></td>
	                            					<td></td>
	                            					<td></td>
	                            				</tr>
	                            			</tbody>
	                            		</table>
	                            	</div>
	                            	<!-- /.col-md-12 -->
					            </div>
					            <!-- /.row -->
	                        </div>
	                    </div>
	                    <!-- /.card -->
	                </div>
	                <!-- /.col-md-12 -->
	            </div>
	            <!-- /.row -->
	        </div>
	        <!-- /.container-fluid -->
	    </div>
	    <!-- /.content -->
	</div>
@endsection

@section('scripts')
	<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
	<script>
		$(document).ready(function() {
			$('#role_users').dataTable();
		});
	</script>
@endsection

resources/views/admin/pages/roles/index.blade.php
@extends('admin.layouts.master')

@section('pageTitle', 'Roles')

@section('content')
	<div class="content-wrapper">
	    <!-- Content Header (Page header) -->
	    <div class="content-header">
	        <div class="container-fluid">
	            <div class="row mb-2">
	                <div class="col-sm-6">
	                    <h1 class="m-0 text-dark">Roles</h1>
	                </div><!-- /.col -->
	                
	                <div class="col-sm-6">
	                    <ol class="breadcrumb float-sm-right">
	                        <li class="breadcrumb-item"><a href="#">Roles</a></li>
	                    </ol>
	                </div><!-- /.col -->
	            </div><!-- /.row -->
	        </div><!-- /.container-fluid -->
	    </div>
	    <!-- /.content-header -->

	    <!-- Main content -->
	    <div class="content">
	        <div class="container-fluid">
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="card card-primary card-outline">
	                        <div class="card-body">
	                            <p class="card-text">
	                                Roles
	                            </p>

	                            <div class="row">
	                            	<div class="col-md-12">
	                            		<table id="roles" class="table table text-center">
						            		<thead>
						            			<tr>
						            				<th>ID</th>
						            				<th>Name</th>
						            				<th>Date Created</th>
						            				<th>Actions</th>
						            			</tr>
						            		</thead>

						            		<tbody>
						            			@foreach($roles as $role)
													<tr>
														<td>{{ $role->id }}</td>
														<td>{{ $role->name }}</td>
														<td>{{ $role->created_at }}</td>
														<td>
															<a href="{{ route('admin.roles.edit', $role->id) }}" class="btn btn-primary"><i class="far fa-edit"></i></a>
														</td>
													</tr>
						            			@endforeach
						            		</tbody>
						            	</table>
	                            	</div>
	                            	<!-- /.col-md-12 -->
					            </div>
					            <!-- /.row -->
	                        </div>
	                    </div>
	                    <!-- /.card -->
	                </div>
	                <!-- /.col-md-12 -->
	            </div>
	            <!-- /.row -->
	        </div>
	        <!-- /.container-fluid -->
	    </div>
	    <!-- /.content -->
	</div>
@endsection

@section('scripts')
	<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
	<script>
		$(document).ready(function() {
			$('#roles').dataTable();
		});
	</script>
@endsection