routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function() {
	Route::namespace('Auth')->middleware('guest:admin')->group(function() {
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
	});

	Route::middleware('auth:admin')->group(function() {
		Route::namespace('Auth')->group(function() {
			Route::post('logout', 'LoginController@logout')->name('logout');
		});

		Route::get('/', 'DashboardController@index')->name('dashboard');
		Route::get('/account_settings', 'DashboardController@accountSettings')->name('account_settings');
		Route::post('/account_settings', 'DashboardController@updateAccountSettings')->name('update_account_settings');
		
		Route::get('/admins', 'AdminController@index')->name('admins.index');
		Route::get('/permissions', 'PermissionController@index')->name('permissions.index');
		Route::get('/activity_logs', 'ActivityLogController@index')->name('activity_logs');

		/** Sample */
		Route::get('/samples', 'SampleController@index')->name('samples.index');
		Route::get('/samples/create', 'SampleController@create')->name('samples.create');
		Route::get('/samples/{id}', 'SampleController@show')->name('samples.show');
		Route::get('/samples/{id}/edit', 'SampleController@edit')->name('samples.edit');
		Route::get('/samples/{id}/destroy', 'SampleController@destroy')->name('samples.destroy');

		Route::post('/samples', 'SampleController@store')->name('samples.store');
		Route::post('/samples/{id}', 'SampleController@update')->name('samples.update');

		/** Roles */
		Route::get('/roles', 'RoleController@index')->name('roles.index');
		Route::get('/roles/create', 'RoleController@create')->name('roles.create');
		Route::get('roles/{id}/edit', 'RoleController@edit')->name('roles.edit');
		Route::get('/roles/{id}/destroy', 'RoleController@destroy')->name('roles.destroy');

		/** Users */
		Route::get('/users', 'UserController@index')->name('users.index');
		Route::get('/users/{id}', 'UserController@show')->name('users.show');

		Route::post('/roles', 'RoleController@store')->name('roles.store');
		Route::post('/roles/{id}', 'RoleController@update')->name('roles.update');
	});
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::namespace('Web')->name('web.')->group(function() {
	Route::namespace('Auth')->group(function() {
		Route::middleware('guest:web')->group(function() {
			Route::get('login', 'LoginController@showLoginForm')->name('login');
			Route::post('login', 'LoginController@login')->name('login');
		});
	});
});

app/Models/Sample.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Sample extends Model
{
    protected $fillable = [
    	'name',
    	'image_path',
    	'description',
    ];

    /** Renders */
    public function renderName()
    {
    	return $this->name;
    }

    public function renderImage()
    {
    	$path = asset('storage/default_images/no-image.png');

    	if ($this->image_path):
    		$path = asset('storage/' . $this->image_path);
    	endif;

    	return $path;
    }

    public function renderDescription()
    {
    	return $this->description;
    }
}

app/Http/Controllers/Admin/SampleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Sample;
use Illuminate\Http\Request;

class SampleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $samples = Sample::all();

        return view('admin.pages.sample.index', [
            'samples' => $samples,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.sample.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $vars = $request->except(['_token']);
        Sample::create($vars);

        return redirect(route('admin.samples.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Sample  $sample
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sample = Sample::find($id);

        return view('admin.pages.sample.show', [
            'sample' => $sample,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Sample  $sample
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sample = Sample::find($id);
        
        return view('admin.pages.sample.edit', [
            'sample' => $sample,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Sample  $sample
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $sample = Sample::find($id);
        $vars = $request->except(['_token']);
        $sample->update($vars);

        return redirect(route('admin.samples.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Sample  $sample
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sample = Sample::find($id);
        $sample->delete();

        return redirect(route('admin.samples.index'));
    }
}

resources/views/admin/pages/sample/create.blade.php
@extends('admin.layouts.master')

@section('pageTitle', 'Sample')

@section('content')
	<div class="content-wrapper">
	    <!-- Content Header (Page header) -->
	    <div class="content-header">
	        <div class="container-fluid">
	            <div class="row mb-2">
	                <div class="col-sm-6">
	                    <h1 class="m-0 text-dark">Add Sample</h1>
	                </div><!-- /.col -->
	                
	                <div class="col-sm-6">
	                    <ol class="breadcrumb float-sm-right">
	                        <li class="breadcrumb-item"><a href="#">Samples</a></li>
	                        <li class="breadcrumb-item active"><a href="#">Create</a></li>
	                    </ol>
	                </div><!-- /.col -->
	            </div><!-- /.row -->
	        </div><!-- /.container-fluid -->
	    </div>
	    <!-- /.content-header -->

	    <!-- Main content -->
	    <div class="content">
	        <div class="container-fluid">
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="card card-primary card-outline">
	                        <div class="card-body">
	                            <p class="card-text">
	                                Sample
	                            </p>

	                            <div class="row">
	                            	<div class="col-md-12">
	                            		<form action="{{ route('admin.samples.store') }}" method="POST" enctype="multipart/form-data">
	                            			@csrf

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                        <label for="name">Name</label>
				                                        <input name="name" type="text" class="form-control" id="name" placeholder="Name" value="{{ old('name') }}" required>
				                                    </div>
	                            				</div>

	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                        <label for="image_path">Image</label>
				                                        <input name="image_path" type="file" class="form-control" id="image_path" placeholder="Image" value="{{ old('image') }}">
				                                    </div>
	                            				</div>
	                            			</div>

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                        <label for="description">Description</label>
				                                        <textarea class="form-control" name="description" id="" cols="30" rows="10"></textarea>
				                                    </div>
	                            				</div>
	                            			</div>

	                            			<div class="row">
												<div class="col-md-1">
		                            				<div class="form-group">
		                            					<button class="btn btn-primary form-control">Submit</button>
		                            				</div>
	                            				</div>
	                            			</div>
	                            		</form>
	                            	</div>
	                            	<!-- /.col-md-12 -->
					            </div>
					            <!-- /.row -->
	                        </div>
	                    </div>
	                    <!-- /.card -->
	                </div>
	                <!-- /.col-md-12 -->
	            </div>
	            <!-- /.row -->
	        </div>
	        <!-- /.container-fluid -->
	    </div>
	    <!-- /.content -->
	</div>
@endsection

resources/views/admin/pages/sample/edit.blade.php
@extends('admin.layouts.master')

@section('pageTitle', 'Sample')

@section('content')
	<div class="content-wrapper">
	    <!-- Content Header (Page header) -->
	    <div class="content-header">
	        <div class="container-fluid">
	            <div class="row mb-2">
	                <div class="col-sm-6">
	                    <h1 class="m-0 text-dark">Edit Sample</h1>
	                </div><!-- /.col -->
	                
	                <div class="col-sm-6">
	                    <ol class="breadcrumb float-sm-right">
	                        <li class="breadcrumb-item"><a href="#">Samples</a></li>
	                        <li class="breadcrumb-item active"><a href="#">Edit</a></li>
	                    </ol>
	                </div><!-- /.col -->
	            </div><!-- /.row -->
	        </div><!-- /.container-fluid -->
	    </div>
	    <!-- /.content-header -->

	    <!-- Main content -->
	    <div class="content">
	        <div class="container-fluid">
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="card card-primary card-outline">
	                        <div class="card-body">
	                            <p class="card-text">
	                                Sample
	                            </p>

	                            <div class="row">
	                            	<div class="col-md-12">
	                            		<form action="{{ route('admin.samples.update', $sample->id) }}" method="POST" enctype="multipart/form-data">
	                            			@csrf

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                        <label for="name">Name</label>
				                                        <input name="name" type="text" class="form-control" id="name" placeholder="Name" value="{{ $sample->renderName() }}" required>
				                                    </div>
	                            				</div>
	                            			</div>

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                        <label for="description">Description</label>
				                                        <textarea class="form-control" name="description" id="" cols="30" rows="10">{{ $sample->renderDescription() }}</textarea>
				                                    </div>
	                            				</div>
	                            			</div>

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
	                            						<label for="image_path"></label>
				                                        <img src="{{ $sample->renderImage() }}" alt="" width="100px" height="100px">
				                                        <input type="file" name="image_path" id="image_path" class="form-control mt-2">
				                                    </div>
	                            				</div>
	                            			</div>

	                            			<div class="row">
												<div class="col-md-1">
	                            				<div class="form-group">
	                            					<button class="btn btn-primary form-control">Submit</button>
	                            				</div>
	                            				</div>
	                            			</div>
	                            		</form>
	                            	</div>
	                            	<!-- /.col-md-12 -->
					            </div>
					            <!-- /.row -->
	                        </div>
	                    </div>
	                    <!-- /.card -->
	                </div>
	                <!-- /.col-md-12 -->
	            </div>
	            <!-- /.row -->
	        </div>
	        <!-- /.container-fluid -->
	    </div>
	    <!-- /.content -->
	</div>
@endsection

resources/views/admin/pages/sample/index.blade.php
@extends('admin.layouts.master')

@section('pageTitle', 'Sample')

@section('content')
	<div class="content-wrapper">
	    <!-- Content Header (Page header) -->
	    <div class="content-header">
	        <div class="container-fluid">
	            <div class="row mb-2">
	                <div class="col-sm-6">
	                    <h1 class="m-0 text-dark">Samples</h1>

	                    <a href="{{ route('admin.samples.create') }}" class="btn btn-primary mt-2"><i class="nav-icon fa fa-plus"></i> Add Sample</a>
	                </div><!-- /.col -->
	                
	                <div class="col-sm-6">
	                    <ol class="breadcrumb float-sm-right">
	                        <li class="breadcrumb-item"><a href="#">Samples</a></li>
	                        <li class="breadcrumb-item active"><a href="#">Index</a></li>
	                    </ol>
	                </div><!-- /.col -->
	            </div><!-- /.row -->
	        </div><!-- /.container-fluid -->
	    </div>
	    <!-- /.content-header -->

	    <!-- Main content -->
	    <div class="content">
	        <div class="container-fluid">
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="card card-primary card-outline">
	                        <div class="card-body">
	                            <p class="card-text">
	                                Samples
	                            </p>

	                            <div class="row">
	                            	<div class="col-md-12">
	                            		<table id="samples" class="table table text-center">
						            		<thead>
						            			<tr>
						            				<th>ID</th>
						            				<th>Image</th>
						            				<th>Name</th>
						            				<th>Description</th>
						            				<th>Actions</th>
						            			</tr>
						            		</thead>

						            		<tbody>
						            			@foreach($samples as $sample)
													<tr>
														<td>{{ $sample->id }}</td>
														<td><img src="{{ asset($sample->renderImage()) }}" alt="" height="100px" width="100px"></td>
														<td>{{ $sample->name }}</td>
														<td>{{ $sample->description }}</td>
														<td>
															<a href="{{ route('admin.samples.show', $sample->id) }}" class="btn btn-primary"><i class="far fa-eye"></i></a>
															<a href="{{ route('admin.samples.edit', $sample->id) }}" class="btn btn-primary"><i class="far fa-edit"></i></a>
															<a href="{{ route('admin.samples.destroy', $sample->id) }}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
														</td>
													</tr>
						            			@endforeach
						            		</tbody>
						            	</table>
	                            	</div>
	                            	<!-- /.col-md-12 -->
					            </div>
					            <!-- /.row -->
	                        </div>
	                    </div>
	                    <!-- /.card -->
	                </div>
	                <!-- /.col-md-12 -->
	            </div>
	            <!-- /.row -->
	        </div>
	        <!-- /.container-fluid -->
	    </div>
	    <!-- /.content -->
	</div>
@endsection

@section('scripts')
	<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
	<script>
		$(document).ready(function() {
			$('#samples').dataTable();
		});
	</script>
@endsection

resources/views/admin/pages/sample/show.blade.php
@extends('admin.layouts.master')

@section('pageTitle', 'Sample')

@section('content')
	<div class="content-wrapper">
	    <!-- Content Header (Page header) -->
	    <div class="content-header">
	        <div class="container-fluid">
	            <div class="row mb-2">
	                <div class="col-sm-6">
	                    <h1 class="m-0 text-dark">Show Sample</h1>

	                    <a href="{{ route('admin.samples.edit', $sample->id) }}" class="btn btn-primary mt-2">Edit Sample</a>
	                </div><!-- /.col -->
	                
	                <div class="col-sm-6">
	                    <ol class="breadcrumb float-sm-right">
	                        <li class="breadcrumb-item"><a href="#">Samples</a></li>
	                        <li class="breadcrumb-item active"><a href="#">Show</a></li>
	                    </ol>
	                </div><!-- /.col -->
	            </div><!-- /.row -->
	        </div><!-- /.container-fluid -->
	    </div>
	    <!-- /.content-header -->

	    <!-- Main content -->
	    <div class="content">
	        <div class="container-fluid">
	            <div class="row">
	                <div class="col-md-12">
	                    <div class="card card-primary card-outline">
	                        <div class="card-body">
	                            <p class="card-text">
	                                {{-- Sample --}}
	                            </p>

	                            <div class="row">
	                            	<div class="col-md-12">
	                            		<form action="{{ route('admin.samples.update', $sample->id) }}" method="POST" enctype="multipart/form-data">
	                            			@csrf

	                            			<div class="row">
	                            				<div class="col-md-6">
				                                    <p><strong>Name</strong></p>
				                                    <p>{{ $sample->renderName() }}</p>
	                            				</div>
	                            			</div>

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                       <p><strong>Description</strong></p>
				                                    <p>{{ $sample->renderDescription() }}</p>
				                                    </div>
	                            				</div>
	                            			</div>

	                            			<div class="row">
	                            				<div class="col-md-6">
	                            					<div class="form-group">
				                                    	<p><strong>Image</strong></p>
				                                        <img src="{{ $sample->renderImage() }}" alt="" width="100px" height="100px">
				                                    </div>
	                            				</div>
	                            			</div>
	                            		</form>
	                            	</div>
	                            	<!-- /.col-md-12 -->
					            </div>
					            <!-- /.row -->
	                        </div>
	                    </div>
	                    <!-- /.card -->
	                </div>
	                <!-- /.col-md-12 -->
	            </div>
	            <!-- /.row -->
	        </div>
	        <!-- /.container-fluid -->
	    </div>
	    <!-- /.content -->
	</div>
@endsection